### ISSUE TITLE
Nfc-tag

### ISSUE THREAD

**Issue by FalcoZTL** [wansors/myfaba-hacks#1]
It seems that an empty NFC tag, written with the folder code, is not working, but a MyFaba figure (which can be erased and rewritten) when written with the code, activates the custom folder.

**Comment by wansors** [comment]
Hi, I tested different types of NFC tags but only made it work with this ones:
_NFC Stickers, Ntag213 NFC Tags, 25mm White Blank NFC Circular Sticker, Writable And Programmable, 144 Bytes Memory, Compatible With NFC Enabled Devices_

On NFC tools you should see the TAG type, mines are like this:
![image](https://github.com/user-attachments/assets/a29a1306-6510-4bdf-b97b-53404383b7c8)

**Comment by freedreamer82** [comment]
Same problem here. Do u have an Amazon link to buy with working tags? 
Thanks

M.

**Comment by wansors** [comment]
Hi, I bought mine at Temu:
https://www.temu.com/goods.html?_bg_fs=1&goods_id=601099537125301&sku_id=17592302840204&_x_msgid=186-20240802-06-B-761359675715891200-506-lXApvzaa&_x_src=mail&_x_sessn_id=p3fpcfbojw&refer_page_name=bgt_order_detail&refer_page_id=10045_1725741755160_3dugp0v8uv&refer_page_sn=10045

**Comment by freedreamer82** [comment]
thanks i'll try them.

M.

**Comment by FalcoZTL** [comment]
Just for share, this one works:
22 pezzi NTAG213 Adesivi Tag NFC, Stickers NFC Rotondi da 25 mm 144 Byte di Memoria Completamente Programmabili, RFID Tags 13,56 MHz Compatibile con Tutti Gli Smartphone Dotati di NFC
 https://amzn.eu/d/h7ABmvL

Company: BABIQT

**Comment by sgregori** [comment]
https://www.amazon.es/dp/B07Q7FZDSC

Another tags working fine.

**Comment by e16384** [comment]
The problem of not working tags, could be the tag IDs of original tags? Usually the tag ID is not copy when clone a tag.
I have 3 originals figures and all of them the ID are: 53:.. :00:01  so all of them start on 53 and finish with 00:01
I don't think in the FABA box are saved all originals ID but maybe just check if the ID stars with 53 or ends with 00:01, could be?

My Aliexpress tags that not works, star with: 1D:...:10:80 maybe this could be the problem.

For someone with working tag: What IDs has the working new nfc tags?

I think there are 'magic tags' that allow to write the ID you want, maybe with this it's possible to clone from the original (included the ID) and change the figure number?

If I rewrite another figure ID in a original FABA figure, it works! (sounds the new figure).
